print("This program will be used to remember your birthday!")
ubday= int(input("Please enter Uti's birthday!"))
tbday= int(input("Please enter Tarun's birthday!"))
rbday= int(input("Please enter Ram's birthday!"))
sbday= int(input("Please enter Suba's birthday!"))
pbday= int(input("Please enter Patti's birthday!"))
print("Uti's birthday is", ubday, "!")
print("Tarun's birthday is", tbday, "!")
print("Ram's birthday is", rbday, "!")
print("Suba's birthday is", sbday, "!")
print("Paati's birthday is", pbday, "!")
print("Thank you for viewing! \n Good day!")